version: '3.8'

services:
  daemon:
    build: .
    volumes:
      - ${WATCHED_DIRECTORY:-./watched_directory}:/watch
      - ${LOG_DIR:-./logs}:/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/logs/daemon.log"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 